project:
  type: website
  output-dir: docs

website:
  title: "My Quarto Blog"
  navbar:
    right:
      - text: "Blog" 
        href: blog/index.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



